import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

<<<<<<< HEAD
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { ThemeProvider } from "@/components/providers/theme-providers";
import { Toaster } from "@/components/ui/sonner";

=======
>>>>>>> e2ec2f644d538822c65cf5d61c11ea2cb26cb473
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

<<<<<<< HEAD
export default async function RootLayout({
=======
export default function RootLayout({
>>>>>>> e2ec2f644d538822c65cf5d61c11ea2cb26cb473
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
<<<<<<< HEAD

  const session = await auth()

  return (
    <SessionProvider session={session}>
=======
  return (
>>>>>>> e2ec2f644d538822c65cf5d61c11ea2cb26cb473
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex flex-col min-h-screen">
              <Toaster/>
    <div className="flex-1">
{children}
    </div>
            </div>
        
        </ThemeProvider>
      </body>
    </html>
    </SessionProvider>
  );
}
=======
        {children}
      </body>
    </html>
  );
}
>>>>>>> e2ec2f644d538822c65cf5d61c11ea2cb26cb473
